# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ValidacaoCPF' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ValidacaoCPF

pod 'CPF-CNPJ-Validator'

end
